- name: Copy and execute env setup and test script
  script: scripts/runtests
  become: true
  ignore_errors: yes
  register: cmd_res
  failed_when: '"=========================== short test summary info ============================" not in cmd_res.stdout' 
  args:
    chdir: "{{ selenium_tests_temp.path  }}"

